JuliaQuantumControl/GRAPE.jl

- examples/simple_state_to_state.jl
- src/backend_lbfgsb.jl
- src/backend_optim.jl
- src/optimize.jl
- src/workspace.jl
This uses automatic gradients, making the `gradient` parameter optional.  Gradients are determined directly from the passed `J_T`, either by selecting the appropriate implementation of the analytic gradient, or by constructing a routine via automatic differentiation (via Zygote).
In addition, we can evaluate `∇J_T` not just via a chain rule with respect to overlaps `τ_k` as we have done so far, but also via a chain rule with respect to the forward-propagated states. This allows to set automatic gradients for functionals that cannot be written in terms of overlaps, and/or of objectives that do not define a `target_state`.
This required a major rewrite of the core algorithm: Before, we would backward-propagate the target states, and then forward-propagate the combined initial states and …
> Change: use automatic gradient

- src/backend_lbfgsb.jl
- src/backend_optim.jl
This fixes the output of print_table during the optimization so that it works in Jupyter notebooks or when piping output to a file (e.g., on a cluster) by flushing stdout after each iteration.
Without this, nothing was being printed while the optimization was still running.
> Fix: flush stdout in `print_table`

- examples/perfect_entanglers.jl
> Extend the perfect-entanglers example to show a standard gate optimization

- examples/perfect_entanglers.jl
- src/workspace.jl
They shouldn't be a required property of an optimization problem: Not all optimization methods use them, plus it's possible to have meaningful defaults
> Make `pulse_options` optional

- src/backend_lbfgsb.jl
- src/backend_optim.jl
- src/optimize.jl
- src/workspace.jl
This adds three new options to `optimize_grape`:
* `J_a`
* `lambda_a`
* `grad_J_a`
> Add support for running costs on the pulse values

- src/backend_lbfgsb.jl
- src/backend_optim.jl
- src/optimize.jl
- src/workspace.jl
the `optimize_grape` routine can now be called with an `upper_bound` and `lower_bound` parameter. For time-dependent bounds, or different bounds on different pulses, it is also possible to give `pulse_options` with keys `upper_bounds` and `lower_bounds`.
This is only implemented for the L-BFGS-B backend. I couln't really figure out how to add bounds to Optim.jl.
https://github.com/JuliaQuantumControl/QuantumControl.jl/issues/15
> Implement L-BFGS-B bounds

- test/runtests.jl
- test/test_pulse_optimization.jl
Specifically, test that the optimization does not mutate guess pulses.
See https://github.com/JuliaQuantumControl/Krotov.jl/issues/28
> Add test for optimization with pulses

- src/optimize.jl
This prevents data loss in case of an unexpected termination when running in non-interactive mode
> Set `atexit` in `@optimize_or_load`

- src/workspace.jl
- test/runtests.jl
- test/test_empty_optimization.jl
Trying to run `optimize` when there were no controls in the problem would produce a very non-obvious deep inside the optimizer. Since this is an easy mistake to make, we can catch this situation with a proper error message.
Reported by @leonbello on Slack.
Cf. https://github.com/JuliaQuantumControl/Krotov.jl/pull/32
> Catch empty controls in optimization

- src/optimize.jl
If an explicit `chi` is given, do not evaluate one with AD. This fix mostly just avoids a spurious and confusing `@info` message.
> Avoid unnecessary evaluation of chi

- docs/make.jl
- docs/src/refs.bib
- src/optimize.jl
- src/result.jl
- src/workspace.jl
- test/test_empty_optimization.jl
- test/test_pulse_optimization.jl
As a side effect, it is now possible to pass propagation keyword arguments to the trajectory.
See https://github.com/JuliaQuantumControl/QuantumControlBase.jl/pull/72
> Adapt to renaming of "objective" to "trajectory"

- Project.toml
- ext/GRAPELBFGSBExt.jl
- ext/GRAPEOptimExt.jl
- src/GRAPE.jl
- src/optimize.jl
- src/workspace.jl
This is a "pretend" package extension, for symmetry with the Optim extension. It's not possible to have a package extension triggered by a hard dependency, so this uses `include` instead.
However, if we ever wanted to switch the default backend, this makes that easy, as we'd only have to tweak the import in `src/GRAPE.jl` and the list of `[extensions]` in the main `Project.toml`.
> Refactor LBFGSB code into `ext` folder

- Project.toml
- ext/GRAPEKrotovExt.jl
- src/result.jl
- test/test_tls_optimization.jl
Implementing `Base.convert` between the different Result objects allows `continue_from` to work.
> Allow to continue Krotov optimization in GRAPE and vice versa

- ext/GRAPELBFGSBExt.jl
- ext/GRAPEOptimExt.jl
- src/optimize.jl
- src/result.jl
- src/workspace.jl
- test/runtests.jl
- test/test_iterations.jl
- test/test_tls_optimization.jl
See https://github.com/JuliaQuantumControl/QuantumControlBase.jl/pull/84
This also enables the new `store_iter_info` argument.
> Combine info-hook/update-hook into `callback`

- docs/make.jl
- ext/GRAPELBFGSBExt.jl
- src/optimize.jl
- src/result.jl
- src/workspace.jl
The `chi!` functions previously used by GRAPE and Krotov are now simply `chi` do not act in-place. This is more general and easier to implement for the user, as it allows to use immutable structs for states
Note that in extreme performance-critical situations, one could still construct the χ-states in-place via a closure or functor.
Both chi and J_T can now have an optional keyword argument `tau` (instead of the previous improperly implemented and unicode `τ`). Whether or not `tau` should be passed to these functions is automatically detected.
> Make `chi` functions not-in-place

- src/optimize.jl
based on our discussion today, fixed a bug in the GRAPE optimizer that occurs if Nr. of trajectories != Nr. of amplitudes
> quick fix for a bug in GRAPE optimizer

- src/optimize.jl
- test/runtests.jl
- test/test_pulse_running_cost.jl
This fixes a bug where giving `grad_J_a` manually would still call the `make_grad_J_a` function, which would then fail.
> Fix using a manual `grad_J_a`

- src/optimize.jl
- test/test_pulse_running_cost.jl
See https://github.com/JuliaQuantumControl/QuantumControl.jl/pull/76
This isn't breaking unless someone was giving a manual `grad_J_a`, which wasn't fully supported until after the last release.
> Adapt to `grad_J_a` not being in-place

- src/optimize.jl
- test/test_tls_optimization.jl
An optimization with `gradient_method=:taylor` would fail if the generator evaluates to an immutable operator
> Fix Taylor gradient for static operators

- src/workspace.jl
An internal `Trajectory` was constructed incorrectly.  This was causing an error for trajectories with extra keyword arguments
> Fix optimization for trajectories with extra keyword args

- src/optimize.jl
- src/workspace.jl
- test/test_tls_optimization.jl
The documentation implied that `prop_callback` was supported, but in fact, that feature hadn't been implemented.
> Add support for `prop_callback`

- docs/make.jl
- ext/GRAPELBFGSBExt.jl
- ext/GRAPEOptimExt.jl
- src/optimize.jl
- src/result.jl
- src/workspace.jl
- test/test_iterations.jl
Adds the `print_iter_info` option, which gives access to a greatly increased number of fields. Modifies the default fields to make more sense in the presence of running costs.
> Allow to configure which info is printed per iteration

- src/optimize.jl
- src/result.jl
- src/workspace.jl
Normalizing χ prior to the backward propagation should increase numerical stability and allow to detect vanishing gradients.
To make all of this easier to debug and test, this also refactors the `optimize_grape` function into new  `evaluate_functional` and `evaluate_gradient!` that properly document the side effects on the GRAPE workspace from evaluating the functional or the gradient
> Refactor to use  `evaluate_functional` and `evaluate_gradient!`, normalize χ

- ext/GRAPELBFGSBExt.jl
- ext/GRAPEOptimExt.jl
- src/optimize.jl
- src/workspace.jl
- test/runtests.jl
- test/test_lbfgsb_saddle_point.jl
This should prevent getting stuck in saddle points, or generally, aborting and optimization because L-BFGS-B thinks it has converged. We can the convergence check to happen inside GRAPE, not inside L-BFGS-B
Closes #85
> Use high-precision flags for LBFGSB
